# Generated by Django 2.2.6 on 2020-07-04 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('desc', models.TextField(default='', null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('anonymous', models.BooleanField(default=True)),
                ('style', jsonfield.fields.JSONField(default={'bgcolor': '#b3daff', 'head': '#ffccff', 'theme': '#b3ffb3'}, null=True)),
                ('access_code', models.TextField(default='openquiz', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.DateTimeField(auto_now=True)),
                ('std_code', models.TextField(default='', null=True)),
                ('access_code', models.TextField(default='showmeresult', null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.Quiz')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('desc', models.TextField(default=None, null=True)),
                ('qtype', models.IntegerField()),
                ('order', models.IntegerField()),
                ('pmarks', models.IntegerField(default=4)),
                ('nmarks', models.IntegerField(default=0)),
                ('answer', models.TextField(default='', null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='PQresponseQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textans', models.TextField(default='', null=True)),
                ('options', jsonfield.fields.JSONField(default={}, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.QuestionQ')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.ResponseQ')),
            ],
        ),
        migrations.CreateModel(
            name='OptionQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('isans', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.QuestionQ')),
            ],
        ),
    ]
