# Generated by Django 2.2.6 on 2020-07-04 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('desc', models.TextField(default='', null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('anonymous', models.BooleanField(default=True)),
                ('style', jsonfield.fields.JSONField(default={'bgcolor': '#b3daff', 'head': '#ffccff', 'theme': '#b3ffb3'}, null=True)),
                ('access_code', models.TextField(default='opensurvey', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyapp.Survey')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('desc', models.TextField(default=None, null=True)),
                ('qtype', models.IntegerField()),
                ('order', models.IntegerField()),
                ('required', models.BooleanField()),
                ('other', models.BooleanField()),
                ('constraint', jsonfield.fields.JSONField(default={}, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyapp.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='PQresponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textans', models.TextField(default='', null=True)),
                ('options', jsonfield.fields.JSONField(default={}, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyapp.Question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyapp.Response')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyapp.Question')),
            ],
        ),
    ]
